Npred: 10

Q: [[15, 0, 0, 0, 0, 0],
    [0, 15, 0, 0, 0, 0],
    [0, 0, 50, 0, 0, 0],
    [0, 0, 0, 5, 0, 0],
    [0, 0, 0, 0, 5, 0],
    [0, 0, 0, 0, 0, 5]]

R: [[0.6, 0, 0],
    [0, 0.6, 0],
    [0, 0, 0.75]]

Qto: [[15, 0, 0, 0, 0, 0],
      [0, 15, 0, 0, 0, 0],
      [0, 0, 50, 0, 0, 0],
      [0, 0, 0, 5, 0, 0],
      [0, 0, 0, 0, 5, 0],
      [0, 0, 0, 0, 0, 5]]

Rto: [[0.6, 0, 0],
      [0, 0.6, 0],
      [0, 0, 0.75]]